# Generated by Django 3.2.7 on 2021-11-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleDataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="How to contact the person", max_length=100
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part_of_day_created",
                    models.CharField(
                        choices=[
                            ("morning", "After 6am, Before 12pm"),
                            ("afternoon", "Between 12pm and 6pm"),
                            ("night", "Between 6am and 6pm"),
                        ],
                        default="morning",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "example data",
                "verbose_name_plural": "example data",
                "ordering": ("-created_at", "name"),
                "get_latest_by": "created_at",
            },
        ),
    ]
