name: Test Django

on: [pull_request]

jobs:
  test-django:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: '17'
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Install sqlalchemy
        run: pip install sqlalchemy
      - name: Install psycopg2
        run: pip install psycopg2 psycopg2-binary
      - name: Create required schemas
        run: python database-setup.py
      - name: Run tests
        run: python app/manage.py test app/
        env:
          ENVIRONMENT_DESCRIPTION: TEST
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
